include = ["pyproject.toml", "dateutilx/**/*.py", "tests/**/*.py"]
line-length = 120
output-format = "concise"
target-version = "py311"

[format]
docstring-code-line-length = 100
skip-magic-trailing-comma = true

[lint]
select = ["F", "E", "W", "B", "I", "PL", "RUF005", "RUF010"]
ignore = ["E203", "E501", "B028", "B905", "PLC0415", "PLR0124", "PLW0603", "PLW1641", "PLW2901"]

[lint.per-file-ignores]
"*/__init__.py" = ["F401"]

[lint.isort]
split-on-trailing-comma = false
combine-as-imports = false

[lint.pylint]
allow-magic-value-types = ["bytes", "int", "str"]
max-args = 21
max-bool-expr = 15
max-branches = 63
max-locals = 52
max-public-methods = 45
max-returns = 7
max-statements = 180
